name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  flutter_vector_icons: ^2.0.0
  google_fonts: ^5.1.0
  flutter_svg: ^1.0.0
  lottie: ^2.0.0
  animations: ^2.0.0
  dynamic_color: ^1.0.0
  validators: ^3.0.0
  flutter_riverpod: ^2.0.0
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  provider: ^6.0.5
  animated_text_kit: ^4.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  local_auth: ^2.1.5
  flutter_animate: ^4.2.0
  flutter_neumorphic: ^3.2.0
  glassmorphism: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
